esphome:
  name: deskrelay
  friendly_name: Desk Relay
  on_boot:
    priority: 800
    then:
      - output.turn_on: relay_oe

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: ".fritz.box"

# Enable web server for OTA
web_server:
  port: 80

ota:
  - platform: web_server

# Output enable pin
output:
  - platform: gpio
    pin: GPIO5
    id: relay_oe

# Shift register
sn74hc595:
  - id: shift_register
    data_pin: GPIO14
    clock_pin: GPIO13
    latch_pin: GPIO12
    sr_count: 2

# Switches for individual relay
switch:
  - platform: gpio
    name: "PC"
    id: relay_1
    pin: { sn74hc595: shift_register, number: 0 }
    restore_mode: ALWAYS_ON
    icon: "mdi:desktop-tower"

  - platform: gpio
    name: "Speaker Right"
    id: relay_2
    pin: { sn74hc595: shift_register, number: 1 }
    restore_mode: ALWAYS_ON
    icon: "mdi:speaker"

  - platform: gpio
    name: "Astro"
    id: relay_3
    pin: { sn74hc595: shift_register, number: 2 }
    restore_mode: ALWAYS_ON
    icon: "mdi:headset"

  - platform: gpio
    name: "Monitor Right"
    id: relay_4
    pin: { sn74hc595: shift_register, number: 3 }
    restore_mode: ALWAYS_ON
    icon: "mdi:monitor"

  - platform: gpio
    name: "Desk Power Socket"
    id: relais_5
    pin: { sn74hc595: shift_register, number: 4 }
    restore_mode: ALWAYS_ON
    icon: "mdi:power-socket-de"

  - platform: gpio
    name: "KVM Switch"
    id: relay_6
    pin: { sn74hc595: shift_register, number: 5 }
    restore_mode: ALWAYS_ON
    icon: "mdi:dip-switch"

  - platform: gpio
    name: "Monitor Lamp"
    id: relay_7
    pin: { sn74hc595: shift_register, number: 6 }
    restore_mode: ALWAYS_ON
    icon: "mdi:desk-lamp"

  - platform: gpio
    name: "Adjustable Desk"
    id: relay_8
    pin: { sn74hc595: shift_register, number: 7 }
    restore_mode: ALWAYS_ON
    icon: "mdi:desk"

  - platform: gpio
    name: "Walking Pad"
    id: relay_9
    pin: { sn74hc595: shift_register, number: 8 }
    restore_mode: ALWAYS_ON
    icon: "mdi:walk"

  - platform: gpio
    name: "Laptop"
    id: relay_10
    pin: { sn74hc595: shift_register, number: 9 }
    restore_mode: ALWAYS_ON
    icon: "mdi:laptop"

  - platform: gpio
    name: "Speaker Left"
    id: relay_11
    pin: { sn74hc595: shift_register, number: 10 }
    restore_mode: ALWAYS_ON
    icon: "mdi:speaker"

  - platform: gpio
    name: "LEDs"
    id: relay_12
    pin: { sn74hc595: shift_register, number: 11 }
    restore_mode: ALWAYS_ON
    icon: "mdi:led-strip-variant"

  - platform: gpio
    name: "Monitor Left"
    id: relay_13
    pin: { sn74hc595: shift_register, number: 12 }
    restore_mode: ALWAYS_ON
    icon: "mdi:monitor"

  - platform: gpio
    name: "BT Dongle Speakers"
    id: relay_14
    pin: { sn74hc595: shift_register, number: 13 }
    restore_mode: ALWAYS_ON
    icon: "mdi:bluetooth"

  - platform: gpio
    name: "Relay 15/Unused"
    id: relay_15
    pin: { sn74hc595: shift_register, number: 14 }
    restore_mode: ALWAYS_ON
    icon: "mdi:circle-off-outline"

  - platform: gpio
    name: "Relay 16/Unused"
    id: relay_16
    pin: { sn74hc595: shift_register, number: 15 }
    restore_mode: ALWAYS_ON
    icon: "mdi:circle-off-outline"


